#!/usr/bin/env bash
# AI Notes - 自动优化与进度同步脚本
# 每30分钟运行一次

set -e

PROJECT_DIR="/root/ai_notes_project"
cd "$PROJECT_DIR"

echo "=========================================="
echo "AI Notes 自动优化任务 - $(date)"
echo "=========================================="

# 激活虚拟环境
source "$PROJECT_DIR/venv/bin/activate"

# 设置 PATH 包含 kimi
export PATH="$HOME/.local/bin:$PATH"

# 定义优化任务指令（可以根据需要调整）
OPTIMIZATION_TASKS=(
    "检查并修复代码中的潜在问题"
    "优化数据库查询性能"
    "添加更多错误处理"
    "改进前端用户体验"
    "补充单元测试"
    "优化 Markdown 渲染"
    "添加数据验证"
    "改进 API 文档"
)

# 随机选择一个优化任务
TASK=${OPTIMIZATION_TASKS[$RANDOM % ${#OPTIMIZATION_TASKS[@]}]}

echo "当前优化任务: $TASK"

# 让 Kimi 执行优化
kimi --print --prompt "
请继续优化 AI Notes 项目。

当前任务: $TASK

项目路径: $PROJECT_DIR

请检查现有代码，找出可以改进的地方，并实施优化。完成后，请更新 DEVELOPMENT.md 文件，记录你完成的优化内容。

注意：
- 保持现有功能正常
- 遵循现有代码风格
- 不要删除或破坏已有功能
- 只做有意义的改进
" --work-dir "$PROJECT_DIR" --model k2p5 --yolo > /tmp/kimi_optimization_$(date +%s).txt 2>&1

echo "Kimi 优化完成"

# 等待一下让文件写入完成
sleep 5

# 检查是否有新的文件变更
if git status --porcelain | grep -q .; then
    echo "检测到代码变更，更新 DEVELOPMENT.md..."
    
    # 更新 DEVELOPMENT.md，添加新的完成项
    python3 << 'PYEOF'
from datetime import datetime
import re

# 读取当前 DEVELOPMENT.md
with open('DEVELOPMENT.md', 'r', encoding='utf-8') as f:
    content = f.read()

# 查找开发日志部分
log_section = "## 📈 开发日志"
if log_section in content:
    # 在开发日志部分添加新条目
    today = datetime.now().strftime('%Y-%m-%d')
    new_entry = f"\n### {today}\n- ✅ 自动优化任务完成\n- 🔧 优化内容: $TASK\n- 📝 Kimi 已自动更新代码和文档"
    
    # 插入到开发日志部分之后
    parts = content.split(log_section)
    if len(parts) > 1:
        after_log = parts[1].split('\n', 1)[1] if '\n' in parts[1] else parts[1]
        content = parts[0] + log_section + new_entry + '\n' + after_log

# 写回文件
with open('DEVELOPMENT.md', 'w', encoding='utf-8') as f:
    f.write(content)

print("✅ DEVELOPMENT.md 已更新")
PYEOF

    # Git 提交
    git add .
    git commit -m "Auto-optimization: $TASK\n\n- Kimi 自动优化任务\n- 更新 DEVELOPMENT.md 进度记录" -m "Generated by OpenClaw Agent"
    
    # 推送到 GitHub
    git push origin main
    echo "✅ 已推送到 GitHub"
else
    echo "ℹ️ 无代码变更，跳过提交"
fi

echo "=========================================="
echo "任务完成"
echo "=========================================="
