#!/usr/bin/env bash
# AI Notes 主动开发脚本 - 每30分钟推进一个功能

set -e

PROJECT_DIR="/root/ai_notes_project"
cd "$PROJECT_DIR"

echo "[$(date)] 开始开发任务" >> /var/log/ai_notes_development.log

# 激活虚拟环境
source "$PROJECT_DIR/venv/bin/activate"
export PATH="$HOME/.local/bin:$PATH"

# 定义开发任务队列（按优先级）
TASKS=(
    "添加笔记分享功能：生成分享链接、权限控制、过期时间"
    "添加数据备份功能：自动备份到文件、恢复机制"
    "添加富文本编辑器：支持图片上传、附件"
    "添加标签管理：创建、编辑、删除标签，标签颜色"
    "添加笔记搜索历史：记录搜索关键词、快速访问"
    "添加暗色主题：切换主题、主题偏好保存"
    "添加移动端优化：PWA支持、移动端手势"
    "添加协作功能：实时协作、冲突解决"
    "添加数据统计：笔记数量、字数统计、写作习惯"
    "添加导出增强：支持PDF、Word格式"
)

# 根据日期轮询选择任务
DAY_OF_YEAR=$(date +%j)
TASK_INDEX=$((DAY_OF_YEAR % ${#TASKS[@]}))
TASK="${TASKS[$TASK_INDEX]}"

echo "今日开发任务: $TASK" >> /var/log/ai_notes_development.log

# 运行 Kimi 开发任务
kimi --print --prompt "
请继续开发 AI Notes 项目。

当前开发任务：$TASK

项目路径: $PROJECT_DIR

要求：
1. 完整实现该功能，包括数据模型、API、前端界面
2. 遵循现有代码架构和风格
3. 确保与已有功能兼容
4. 更新 README.md 和 DEVELOPMENT.md
5. 不要破坏现有功能

请开始实现。
" --work-dir "$PROJECT_DIR" --model k2p5 --yolo > /tmp/kimi_dev_$(date +%s).txt 2>&1

echo "Kimi 开发完成，检查变更..." >> /var/log/ai_notes_development.log

# 等待文件写入
sleep 10

# 检查是否有变更
if git status --porcelain | grep -q .; then
    echo "检测到新功能开发，更新文档并推送..." >> /var/log/ai_notes_development.log

    # 更新 DEVELOPMENT.md
    python3 << 'PYEOF'
from datetime import datetime

with open('DEVELOPMENT.md', 'r', encoding='utf-8') as f:
    content = f.read()

today = datetime.now().strftime('%Y-%m-%d')
new_entry = f"\n### {today}\n- 🚀 Phase 2 功能开发\n- 📌 完成：$TASK\n- ✅ 状态：已完成并推送"

log_marker = "## 📈 开发日志"
if log_marker in content:
    parts = content.split(log_marker)
    after_log = parts[1].split('\n', 1)[1] if '\n' in parts[1] else parts[1]
    content = parts[0] + log_marker + new_entry + '\n' + after_log

with open('DEVELOPMENT.md', 'w', encoding='utf-8') as f:
    f.write(content)

print("DEVELOPMENT.md updated")
PYEOF

    # 提交并推送
    git add .
    git commit -m "Feature: $TASK" -m "Auto-generated by Kimi development task" || true
    git push origin main || true

    echo "[$(date)] 开发完成并已推送" >> /var/log/ai_notes_development.log
else
    echo "[$(date)] 无代码变更，可能功能已存在或无需修改" >> /var/log/ai_notes_development.log
fi

echo "[$(date)] 任务结束" >> /var/log/ai_notes_development.log
